const CartActiontypes = {
    TOGGEL_CART_HIDDEN: 'TOGGEL_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    CLEARE_CART: 'CLEARE_CART'
}
export default CartActiontypes;